# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MQTTSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTTSample
  pod 'MQTTClient'
  pod 'MessageKit'
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
  
end
